### ISSUE TITLE
Nice to have: Fixed position menu

### ISSUE THREAD

**Issue by peterfoeng** [Renobird/AdminThemeReno#5]
Hi Reno,

This is just an idea/discussion regarding the sidebar menu, do you reckon it is better to have a fixed position menu? So when you have a long pages, the menu is still easy to be accessed if the user need to navigate away from the current screen. :)

Cheers

**Comment by mike-anthony** [comment]
+1 :+1:

**Comment by Renobird** [comment]
If you have a lot of navigation items so that the navigation is longer than the viewport, the fixed position makes it impossible to ever reach the items below the viewport. Could check that via JS I suppose. I'll explore some options.

**Comment by mike-anthony** [comment]
What about independent scrolling?

**Comment by Renobird** [comment]
That starts to get real ugly - especially considering that the quick menus would likely need it too. :)

**Comment by mike-anthony** [comment]
Guess so. I must say though, that all these modern admin panels with fixed this and fixed that [they're making](http://themeforest.net/category/site-templates/admin-templates) these days simply wouldn't suit PW. That said, I'm thinking of making one once I'm done with Advanced Redirects.

**Comment by Renobird** [comment]
I've got a bunch of little tweaks to make, and I'm definitely not opposed to a fixed sidebar. I'll explore some options here soon.

**Comment by mike-anthony** [comment]
If you have a fixed sidebar, then you'd also need a fixed header, unless that's moved over and the sidebar goes right to the top. Well, there are a few options to choose from.

**Comment by Renobird** [comment]
The sidebar underwent some changes in the latest version. It's not fixed, but now scrolls independently if the contents overflow the viewport.
