### ISSUE TITLE
Admin Theme Reno translation

### ISSUE THREAD

**Issue by Manfred62** [Renobird/AdminThemeReno#7]
Hi Tom,

we can easy make more strings translatable in AdminThemeReno.module:
line 53-57
line 66-67
line 82
line 87-88
line 95
line 104

the headings "Pages, Setup, Modules, Access" in the Icons section are not translatable?

Also posted this in the PW github repo.

BTW: some corrections needed in this phrase (I'm no english speaker)?
"To use this feature the 'user' template needs to have an image field. If you(*r* or *the*) user template doesn't have an image field, the avatar will default to an icon. To add an image field to the user template *go to* Setup > Templates > Filters (Show System Templates). The 'user' template will now show in the list."

**Comment by Renobird** [comment]
Manfred62, some updates have been made in the latest version.There still may be a few small translation issues — I'll work with Ryan to get them resolved if so.
