### ISSUE TITLE
Admin Theme Reno buttons

### ISSUE THREAD

**Issue by Manfred62** [Renobird/AdminThemeReno#8]
if Reno is activated: in the language section the buttons 'ZIP download' and 'translate new file' are doubled under the top.
![pw-reno-language](https://cloud.githubusercontent.com/assets/5367033/4260224/f3046088-3b30-11e4-81eb-22d0f1b0c357.jpg)

Also posted this in the PW github repo!

**Comment by Renobird** [comment]
I'm not seeing this issue locally, perhaps it was resolved elsewhere? Sorry for the slow response to these issue, I wasn't receiving the notifications.
