### ISSUE TITLE
Page Tree is a bit jumpy

### ISSUE THREAD

**Issue by mikerockett** [Renobird/AdminThemeReno#9]
Hovering over items adds 1px, probably due to the task buttons (edit, view, etc). Makes the tree a bit jumpy.

**Comment by Renobird** [comment]
What browser? Looks fine here.

**Comment by mike-anthony** [comment]
Opera and Chrome latest. Will upload a screencast for you now now.

**Comment by mike-anthony** [comment]
http://ge.tt/9u0YUB82

**Comment by Renobird** [comment]
Hey Mike, I'm having trouble getting the screencast to play. Seems corrupted somehow. 
Can you save it as a .mov or something other than a .flv?

**Comment by mike-anthony** [comment]
Yeah, will do.

**Comment by mike-anthony** [comment]
Done - at the same link.

**Comment by Renobird** [comment]
Thanks.

**Comment by Renobird** [comment]
Are you still seeing this issue? I can't recreate it. Glad to continue exploring if wasn't cleared up with the latest updates.

**Comment by mikerockett** [comment]
Seems to be cleared - thanks Tom.
